export const universalCalculationIntents: string[] = [
    'how to calculate',
    'calculator for',
    'is there a calculator for',
    'formula to calculate',
    'ratio calculator',
    'how do I calculate',
    'is there a tool to calculate',
    'looking for a calculator',
    'estimator for',
    'converter for',
    'generator for',
    'simulator for',
    'como calcular',
    'calculadora para',
    'existe alguna herramienta para calcular'
];

export const allCategorySeeds: string[] = [
    'alcohol BAC',
    'astronomy telescope',
    'audio delay dB',
    'baby feeding percentile',
    'bike gear ratio tire pressure',
    'coffee brew ratio espresso',
    'cooking conversion cups grams',
    'diy woodworking concrete tile',
    'fpv drone battery thrust',
    'education GPA projected grade',
    'file size bitrate bandwidth',
    'finance loan amortization ROI',
    'forensic blood stain trajectory',
    'gaming dice roll probability',
    'hardware mouse double click DPI',
    'health BMI calorie macro',
    'home room lighting HVAC',
    'music tempo delay BPM',
    'nature solar panel wind power',
    'nautical knot tide distance',
    'pet dog cat medication dosage',
    '3d printing filament shrinkage step',
    'science physics three body orbital',
    'sports running pace vo2max',
    'statistics confidence interval p value',
    'streaming bitrate OBS encoder',
    'tabletop RPG encounter difficulty',
    'textile yarn fabric yardage',
    'travel timezone jetlag currency',
    'developer regex cron timestamp'
];
